"""Write docs/release_record.md from committed manifests; never types a number by hand.

    uv run --locked python scripts/write_release_record.py
    uv run --locked python scripts/write_release_record.py --pair <row_level_sweep_id> <grouped_sweep_id>

Lists the generation manifest and every sweep in run_artifacts/sweeps/ (all retained). The
comparison pairs two sweeps explicitly with --pair; otherwise it uses the latest sweep in which
patients overlapped against the latest completed sweep with zero overlap, and says so.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "release_record.md"


def fmt(v, digits=4):
    return "unavailable" if v is None else (f"{v:.{digits}f}" if isinstance(v, float) else str(v))


def load_sweeps():
    sweeps = []
    for path in sorted((ROOT / "run_artifacts" / "sweeps").glob("*.json")):
        s = json.loads(path.read_text(encoding="utf-8"))
        s["_runs"] = []
        for r in s["runs"]:
            mp = ROOT / "run_artifacts" / r["run_id"] / "manifest.json"
            s["_runs"].append(json.loads(mp.read_text(encoding="utf-8")) if mp.exists() else {"run_id": r["run_id"], "missing": True})
        sweeps.append(s)
    return sweeps


def split_label(s):
    code = s.get("split_code") or {}
    where = f"{code.get('repo_relative_path')} @ {str(code.get('repo_git_sha'))[:12]}" if code.get("repo_git_sha") else "unbound"
    return f"`{s['split_function']}` ({where})"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pair", nargs=2, metavar=("ROW_LEVEL_SWEEP", "GROUPED_SWEEP"))
    args = parser.parse_args()

    gen_path = ROOT / "data" / "generation_manifest.json"
    if not gen_path.exists():
        sys.exit("ERROR: data/generation_manifest.json is missing; freeze the dataset first.")
    gen = json.loads(gen_path.read_text(encoding="utf-8"))
    sweeps = load_sweeps()
    by_id = {s["sweep_id"]: s for s in sweeps}

    lines = ["# Release record - invariant-synthetic-nsclc-v1", "",
             "Generated by `scripts/write_release_record.py` from committed manifests. Do not edit by hand.", "",
             "## Frozen dataset", "",
             "| Field | Value |", "|---|---|",
             f"| Generator version | {gen['generator_version']} |",
             f"| Generator commit | `{gen['generator_git_sha']}` |",
             f"| Configuration SHA-256 | `{gen['configuration_sha256']}` |",
             f"| Metadata SHA-256 | `{gen['metadata_sha256']}` |",
             f"| Image manifest SHA-256 | `{gen['image_manifest_sha256']}` |",
             f"| Samples | {gen['sample_count']} |",
             f"| Dependencies | {', '.join(f'{k} {v}' for k, v in gen['dependency_versions'].items())} |", ""]

    lines += ["## All sweeps", ""]
    if not sweeps:
        lines += ["No sweeps recorded yet.", ""]
    for s in sweeps:
        pa = s["patient_auc"]
        lines += [f"### Sweep `{s['sweep_id']}`", "",
                  f"Split: {split_label(s)}. Code commit `{str(s['git_sha'])[:12]}`"
                  f"{' (dirty)' if s.get('git_dirty') else ''}. Metadata `{str(s['metadata_hash'])[:12]}`.", "",
                  "| Seed | Status | Patients in both sets (N) | Test patients (M) | Patient AUC | Slice AUC | Run ID |",
                  "|---|---|---|---|---|---|---|"]
        for m in s["_runs"]:
            met = m.get("metrics") or {}
            lines.append(f"| {m.get('split_seed', '?')} | {m.get('status', 'missing manifest')} | "
                         f"{fmt(met.get('overlap_count'))} | {fmt(met.get('test_patient_count'))} | "
                         f"{fmt(met.get('patient_auc'))} | {fmt(met.get('slice_auc'))} | `{m['run_id']}` |")
        mean = f"{pa['mean']:.4f} ± {pa['population_std']:.4f}" if pa["mean"] is not None else "unavailable"
        lines += ["", f"Patient AUC over defined seeds: {mean} ({pa['defined']}/{pa['total']} defined; "
                      "population standard deviation, not a confidence interval).", ""]

    lines += ["## Comparison", ""]
    pair = None
    if args.pair:
        missing = [p for p in args.pair if p not in by_id]
        if missing:
            sys.exit(f"ERROR: unknown sweep IDs {missing}")
        pair, how = (by_id[args.pair[0]], by_id[args.pair[1]]), "explicit --pair"
    else:
        leaky = [s for s in sweeps if any((v or 0) > 0 for v in s["overlap_count"])]
        clean = [s for s in sweeps if s["overlap_count"] and all(v == 0 for v in s["overlap_count"])
                 and all(r["status"] == "completed" for r in s["runs"])]
        if leaky and clean:
            pair, how = (leaky[-1], clean[-1]), "default: latest sweep with patient overlap vs latest completed zero-overlap sweep"
    if pair is None:
        lines += ["Not available: need one sweep with patient overlap and one completed sweep without.", ""]
    else:
        a, b = pair
        seeds_a = {m["split_seed"]: m for m in a["_runs"] if "split_seed" in m}
        seeds_b = {m["split_seed"]: m for m in b["_runs"] if "split_seed" in m}
        lines += [f"Pairing: {how}. Row-level `{a['sweep_id']}` vs patient-grouped `{b['sweep_id']}`. "
                  "Difference = row-level minus grouped, only for seeds where both are defined. The two splits "
                  "hold out different patients; the difference describes this engineered benchmark only.", "",
                  "| Seed | Row-level patient AUC | Grouped patient AUC | Difference |", "|---|---|---|---|"]
        diffs = []
        for seed in sorted(set(seeds_a) | set(seeds_b)):
            x = (seeds_a.get(seed, {}).get("metrics") or {}).get("patient_auc")
            y = (seeds_b.get(seed, {}).get("metrics") or {}).get("patient_auc")
            d = x - y if x is not None and y is not None else None
            if d is not None:
                diffs.append(d)
            lines.append(f"| {seed} | {fmt(x)} | {fmt(y)} | {fmt(d)} |")
        if diffs:
            mean = sum(diffs) / len(diffs)
            std = (sum((d - mean) ** 2 for d in diffs) / len(diffs)) ** 0.5
            lines += ["", f"Mean difference {mean:.4f} ± {std:.4f} over {len(diffs)} seeds with both values defined."]
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(sweeps)} sweeps)")


if __name__ == "__main__":
    main()
